### ISSUE TITLE
#include "SPIFFS.h"   which is missing in   SPIFFSIniFile.h

### ISSUE THREAD

**Issue by jorail** [yurilopes/SPIFFSIniFile#4]
**Problem:** 
Compilation error on SPIFFSIniFile.h library, see following error message from the Arduino IDE compiler

In file included from C:\Users\rj\Documents\Arduino\libraries\SPIFFSIniFile\src\SPIFFSIniFile.cpp:1:0:
C:\Users\rj\Documents\Arduino\libraries\SPIFFSIniFile\src\SPIFFSIniFile.h: In member function 'bool SPIFFSIniFile::open()':
C:\Users\rj\Documents\Arduino\libraries\SPIFFSIniFile\src\SPIFFSIniFile.h:130:10: error: 'SPIFFS' was not declared in this scope
  _file = SPIFFS.open(_filename, _mode);
          ^

The inclusion of the SPIFFS.h file is needed for using one of its functions in line 130:  _file = SPIFFS.open(_filename, _mode);

**Solution:** 
**manually add one line for including SPIFFS.h library in the SPIFFSIniFile library**

1. search following library source code file: 
\SPIFFSIniFile-1.0.0\src\SPIFFSIniFile.h

2. open in text editor

3. insert:   #include "SPIFFS.h"   after line 9   #include "FS.h"   as follows: 

use line 9 and following in SPIFFSIniFile.h like this:

#include "FS.h"
#include "SPIFFS.h"  // additional line inserted for including missing SPIFFS library
#include "IPAddress.h"

instead of original line 9 and 10 in SPIFFSIniFile.h: 

#include "FS.h"
#include "IPAddress.h"

**Comment by larryl79** [comment]
I had a same issue,

#include <SPIFFS.h>
added to SPIFFSIniFile.h sorted it out, no errors anymore!

please add it to the lib!

**Comment by stephcache** [comment]
Hello, I try to use your library but I get an error:

My code:

`#include "FS.h"
#include "SPIFFS.h"
#include <SPIFFSIniFile.h>

void setup()
{
  const size_t bufferLen = 80;
  char login_wifi[bufferLen];
  char mdp_wifi[bufferLen];
  char smtp_host[bufferLen];
  char smtp_port[bufferLen];
  char login_mail[bufferLen];
  char mdp_mail[bufferLen];
  char nom[bufferLen];
  char mail[bufferLen];
  
  Serial.begin(9600);
  
  SPIFFS.begin();
  
  SPIFFSIniFile ini("config.ini");
  ini.open();
  
  ini.getValue("wifi", "login", login_wifi, bufferLen);
  ini.getValue("wifi", "mdp", mdp_wifi, bufferLen);
  ini.getValue("mail", "smtp_host", smtp_host, bufferLen);
  ini.getValue("mail", "smtp_port", smtp_port, bufferLen);
  ini.getValue("mail", "login", login_mail, bufferLen);
  ini.getValue("mail", "mdp", mdp_mail, bufferLen);
  ini.getValue("client", "nom", nom, bufferLen);
  ini.getValue("client", "mail", mail, bufferLen);
  
  Serial.println(F(login_wifi));
  Serial.println(F(mdp_wifi));
  Serial.println(F(smtp_host));
  Serial.println(F(smtp_port));
  Serial.println(F(login_mail));
  Serial.println(F(mdp_mail));
  Serial.println(F(nom));
  Serial.println(F(mail));
}

void loop() {}`

 Arduino : 1.8.19 (Windows 10), Carte : "ESP32 Wrover Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), QIO, 80MHz, 921600, None, Disabled"

In file included from C:\Users\steph\OneDrive\Bureau\Fichier de teste\carte_SD\carte_SD.ino:6:

C:\Users\steph\OneDrive\Documents\Arduino\libraries\SPIFFSIniFile\src/SPIFFSIniFile.h:31:51: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

  SPIFFSIniFile(const char* filename, char* mode = "r",

                                                   ^~~

C:\Users\steph\OneDrive\Bureau\Fichier de teste\carte_SD\carte_SD.ino: In function 'void setup()':

C:\Users\steph\OneDrive\Bureau\Fichier de teste\carte_SD\carte_SD.ino:28:33: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   SPIFFSIniFile ini("config.txt");

                                 ^

In file included from C:\Users\steph\OneDrive\Documents\Arduino\libraries\SPIFFSIniFile\src\SPIFFSIniFile.cpp:1:

C:\Users\steph\OneDrive\Documents\Arduino\libraries\SPIFFSIniFile\src\SPIFFSIniFile.h:31:51: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

  SPIFFSIniFile(const char* filename, char* mode = "r",

                                                   ^~~

C:\Users\steph\OneDrive\Documents\Arduino\libraries\SPIFFSIniFile\src\SPIFFSIniFile.h: In member function 'bool SPIFFSIniFile::open()':

C:\Users\steph\OneDrive\Documents\Arduino\libraries\SPIFFSIniFile\src\SPIFFSIniFile.h:130:10: error: 'SPIFFS' was not declared in this scope

  _file = SPIFFS.open(_filename, _mode);

          ^~~~~~

C:\Users\steph\OneDrive\Documents\Arduino\libraries\SPIFFSIniFile\src\SPIFFSIniFile.h:130:10: note: suggested alternative: 'SPI_CS1'

  _file = SPIFFS.open(_filename, _mode);

          ^~~~~~

          SPI_CS1

exit status 1

Erreur de compilation pour la carte ESP32 Wrover Module

Ce rapport pourrait être plus détaillé avec
l'option "Afficher les résultats détaillés de la compilation"
activée dans Fichier -> Préférences.

**Comment by jorail** [comment]
The example, where I got it to work two years ago is here: 
https://github.com/jorail/PiedPiperS
or here for the detailed code: 
https://github.com/jorail/PiedPiperS/blob/main/PiedPiperS/PiedPiperS.ino

But this is too long since to remember the details. The solution I found is documented on top of this issue, as good as I could figure it out back then.

**Comment by stephcache** [comment]
I looked at your code, I already had trouble understanding the original code so yours will be without me. I still tried to isolate the part of the code but it doesn't change anything I get the same error.

**Comment by josail** [comment]
You added
 #include "SPIFFS.h"
also in the beginning of the code of the SPIFFSIniFile.h (not only in the level where you include/call SPIFFSIniFile.h?

This was what made it work for me and Larry. If this does not help, I really don't know, sorry.

**Comment by stephcache** [comment]
I don't understand, I would have to put 'SPIFFS.h' where?

**Comment by josail** [comment]
Write it into the intro of the SPIFFSIniFile.h file. You need to add one line in there.

The execution/compilation process of the SPIFFSIniFile.h needs to know itself, that it can access the content of SPIFFS.h

**Comment by stephcache** [comment]
How do we modify the file?

**Comment by jorail** [comment]
Edit the file SPIFFSIniFile.h in the library
I did this by manipulating the library which I had installed in Arduino IDE, then editing with Notepad++, look in your user/documents folder for Arduino/libaries/SPIFFSIniFile/src

Add the orange marked line 9 in the following screenshot

![Add line to SPIFFSIniFile library manually](https://github.com/yurilopes/SPIFFSIniFile/assets/81030176/46369c89-128a-4ac6-b8b2-487413b1eabe)

**Comment by jorail** [comment]
... by the way: If you have a fresh download of the SPIFFSIniFile.h from github, this is already done 20 March 2020 by the following commit to [SPIFFSIniFile.h](https://github.com/yurilopes/SPIFFSIniFile/commit/b0db7c9298c76f59ff15842f46fd7d5b35dafaf4)

Thus, if you agree and if it works for you, too, you can close this issue. Thanks to [Bascy](https://github.com/yurilopes/SPIFFSIniFile/commits?author=Bascy)

**Comment by stephcache** [comment]
Thank you for your help I did not know where were the libraries that we downloaded, all that for just a library update which is not done in ide arduino. I had a duplicate library problem but I can manage. I don't know how to close the discussion.

I have more compilation problem but unfortunately I don't get my values

`//#include <SD.h>
//#include <SPI.h>
//#include <IniFile.h>

#include "FS.h"
#include <SPIFFSIniFile.h>

void setup()
{
  const size_t bufferLen = 80;
  char login_wifi[bufferLen];
  char mdp_wifi[bufferLen];
  char smtp_host[bufferLen];
  char smtp_port[bufferLen];
  char login_mail[bufferLen];
  char mdp_mail[bufferLen];
  char nom[bufferLen];
  char mail[bufferLen];

  Serial.begin(115200);
  SPIFFS.begin(5);
  //SPI.begin();
  //SD.begin(10);

  //IniFile ini("/config.ini");

  SPIFFSIniFile ini("config.ini");
  ini.open();
  
  ini.getValue("wifi", "login", login_wifi, bufferLen);
  ini.getValue("wifi", "mdp", mdp_wifi, bufferLen);
  ini.getValue("mail", "smtp_host", smtp_host, bufferLen);
  ini.getValue("mail", "smtp_port", smtp_port, bufferLen);
  ini.getValue("mail", "login", login_mail, bufferLen);
  ini.getValue("mail", "mdp", mdp_mail, bufferLen);
  ini.getValue("client", "nom", nom, bufferLen);
  ini.getValue("client", "mail", mail, bufferLen);
  
  Serial.println(login_wifi);
  Serial.println(mdp_wifi);
  Serial.println(smtp_host);
  Serial.println(smtp_port);
  Serial.println(login_mail);
  Serial.println(mdp_mail);
  Serial.println(nom);
  Serial.println(mail);

  ini.close();
}

void loop() {}`

`19:36:40.817 -> ets Jul 29 2019 12:21:46
19:36:40.817 -> 
19:36:40.817 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
19:36:40.817 -> configsip: 0, SPIWP:0xee
19:36:40.817 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
19:36:40.864 -> mode:DIO, clock div:1
19:36:40.864 -> load:0x3fff0030,len:1184
19:36:40.864 -> load:0x40078000,len:13220
19:36:40.864 -> ho 0 tail 12 room 4
19:36:40.864 -> load:0x40080400,len:3028
19:36:40.864 -> entry 0x400805e4
19:36:41.097 -> ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮\C@⸮6
@0
19:36:41.144 -> ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮\C@⸮6
@0
19:36:41.190 -> ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮\C@⸮6
@0
19:36:41.238 -> ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮\C@⸮6
@0
19:36:41.238 -> ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮\C@⸮6
@0
19:36:41.284 -> ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮\C@⸮6
@0
19:36:41.284 -> ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮\C@⸮6
@0
19:36:41.284 -> 
`
